version: '3.8'
services:
  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"  # Open to register.
    networks:
      - app-network

  notes-db:
    image: postgres
    environment:
      POSTGRES_DB: studyHubNotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - app-network

  notes-service:
    build:
      context: ./Notes
    environment:
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - notes-db
    networks:
      - app-network

  translator-service:
    build:
      context: ./Translator
    environment:
      - HUGGING_FACE_API_TOKEN=${HUGGING_FACE_API_TOKEN}
      - SERVER_PORT=8084
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

  security-service:
    build:
      context: ./Security
    ports:
      - "8080:8080" # Gateway + auth port
    environment:
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

  security-db:
    image: postgres
    environment:
      POSTGRES_DB: studyHubUsers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - app-network

  main-service:
    build:
      context: ./Main
    environment:
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
