services:
  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"  # Open to register.
    networks:
      - app-network

  main-db:
    image: postgres
    environment:
      POSTGRES_DB: studyHubUsers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - app-network

  notes-db:
    image: postgres
    environment:
      POSTGRES_DB: studyHubNotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - app-network

  notes-service:
    build:
      context: ./Notes
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - notes-db
    networks:
      - app-network

  main-service:
    build:
      context: ./Main
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
