version: '3.8'
services:
  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    networks:
      - app-network

  notes-service:
    build:
      context: ./Notes
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

  translator-service:
    build:
      context: ./Translator
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

  security-service:
    build:
      context: ./Security
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

  main-service:
    build:
      context: ./Main
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8084
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
